#!/bin/env python

"""from toc.tex generated by easychair, extract metadata necessary for toc generation: title, authors"""

import sys

toc = [x.strip() for x in open(sys.argv[1]).readlines()]
index = {}

for line in toc:
    if line.startswith("\\tocTitle{"):
        #print line
        title = "}".join(line.split("}")[:-2])
        #print title
        title = "{".join(title.split("{")[1:])    
        #print title
    elif line.startswith("\\tocAuthors{"):
        #print line
        author =  "{".join(line.split("{")[1:])
        author = author[:-1]
        index[title]=author

for one in index:
    print "%s --> %s"%(one,index[one])
                             
